# Generated by Django 3.0.5 on 2020-04-29 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200428_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pulished', 'Published')], default='draft', max_length=10),
        ),
    ]
